routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Notifications\homestaybooked;
use App\agent;
use App\guest;



Route::get('/', function () {
    return view('homepage');
});

// Auth::routes();

Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

//Agent
Route::get('/agent/login','Auth\LoginController@agentShowLogin')->name('agentLogin');

route::get('/agent/register','Auth\RegisterController@ShowRegisterAgent')->name('agentregister');

Route::get('/agent/edit/{id}', 'AgentController@edit')->name('editagent')->middleware('auth:agent');

Route::post('/agent/register','Auth\RegisterController@RegisterAgent')->name('registeragent');

Route::post('/agent/login','Auth\LoginController@agentlogin')->name('loginagent');

Route::put('/agent/update/{id}/update','AgentController@update')->name('updateagent');

Route::delete('/agent/{agent}', 'AgentController@destroy')->name('agent.destroy');


//Guest
Route::get('/guest/login','Auth\LoginController@guestShowLogin')->name('guestLogin');

route::get('/guest/register','Auth\RegisterController@ShowRegisterGuest')->name('guestregister');

Route::get('/guest/edit/{id}', 'GuestController@edit')->name('editguest')->middleware('auth:guest');

Route::get('guest/view/{id}', 'GuestController@show')->name('guest.show')->middleware('auth:guest');

Route::post('/guest/register','Auth\RegisterController@registerguest')->name('registerguest');

Route::post('/guest/login','Auth\LoginController@guestlogin')->name('loginguest');

Route::put('/guest/update/{id}/update','GuestController@update')->name('updateguest');

Route::delete('/guest/{guest}', 'GuestController@destroy')->name('guest.destroy');



// handle agent and guest

Route::resource('/agent', 'AgentController')->middleware('auth:agent');

Route::resource('/guest', 'GuestController')->middleware('auth:guest');

//homestay

Route::resource('/homestay', 'HomestayController');


//Route::resource('/booking', 'BookingController', ['except' => ['create'] ])->middleware('auth:guest', 'auth:agent');

route::get('/homestay/view', 'HomestayController@show')->name('homestay.view')->middleware('auth:guest');
////
//route::post('/homestay/register', 'HomestayController@store')->name('homestay.store');

//Booking
//Route::get('/booking/create', 'BookingController@create')->middleware('auth:guest')->name('booking.homestay');

route::get('/booking/create/{id}', 'BookingController@create')->name('booking.create')->middleware('auth:guest');

route::post('/booking/store/{id}', 'BookingController@store')->name('booking.store');

route::get('/booking', 'BookingController@index')->name('booking.index')->middleware('auth:guest');

route::delete('/booking/delete/{booking_id}', 'BookingController@destroy')->name('booking.destroy')->middleware('auth:guest');

route::delete('/booking/deleteagent/{booking_id}', 'BookingController@destroyagent')->name('booking.destroyagent')->middleware('auth:agent');


route::get('/booking/detail/{id}', 'BookingController@detail')->name('booking.detail');




//must have 2 unit edit & update
route::get('/booking/edit/{id}', 'BookingController@edit')->name('booking.edit')->middleware('auth:guest');

route::post('/booking/update/{id}','BookingController@update')->name('booking.update');

//
//Route::get('/homestay/{homestay}/edit', 'HomestayController@edit')->name('homestay.edit');
//
//Route::patch('/homestay/{id}', 'HomestayController@update')->name('homestay.update');
//
//Route::delete('/booking/{}', 'HomestayController@destroy')->name('homestay.destroy');

//route::get('/homestay/register', 'HomestayController@registerhome')->name('registerhome');

app/Agent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Agent extends Authenticatable
{
    protected $primaryKey = 'agent_id';

    protected $guard = 'agent';

    protected $table = 'agents';

    protected $guarded = [];


    public function getAuthPassword()
    {
        return $this->agent_pass;
    }
    protected $fillable =
       ['agent_id', 'agent_name','agent_ic','agent_pnum','agent_email','agent_pass'
    ];

}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use App\Agent;
use App\Booking;
use App\Homestay;
use Illuminate\Http\Request;
use App\Http\Requests\updateagent;
//use Illuminate\Http\Requests;
use Illuminate\support\facades\session;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class AgentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $booking = Booking::where('guest_id', Auth::guard('guest')->user()->guest_id)->get();

        $booking= Booking::all();

        $booking = Booking::paginate(5);
        return view('agent.index', compact('booking'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $request->get;
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $agent= Agent::where('agent_id', $id)->first();

        return view('auth.agent.viewagent', compact('agent'));
    }
    /**
     * Show the form for editing the specified resource.
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agent = Agent::where('agent_id', $id)->first();
        if ($agent->agent_id == Auth::user()->agent_id)
        {
            return view('auth.agent.updateagent', compact('agent'));
        }
        else
        {
            return redirect('/agent/home');
        }
    }
    /**
     * Update the specified resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(updateagent $request, $id)
    {
        $agent = Agent::where('agent_id', $id)->first();
        if ($agent){
            if (trim($request->password) == null)
            {
                $input = $request->except('password');
                $agent->update(
                    ['agent_name'=>$input['agent_name'],
                    'agent_ic'=>$input['agent_ic'],
                    'agent_pnum'=>$input['agent_pnum'],
                    'agent_email'=>$input['agent_email']
                    ]);
                Session::flash('update_profile','Update profile successfully');
                return redirect('/agent/'. $id);
            }
            else
            {
                $input = $request->all();
                $input['password'] = Hash::make($input['password']);
                $agent->update(
                   [ 'agent_name'=>$input['agent_name'],
                    'agent_ic'=>$input['agent_ic'],
                    'agent_pnum'=>$input['agent_pnum'],
                    'agent_email'=>$input['agent_email'],
                    'agent_pass'=>$input['password']
                 ]);
                Session::flash('update_profile','Update profile successfully');
                return redirect('/agent/'. $id);
            }
        }
        else
            {
            return redirect('/agent/home');
            }
    }
    /**
     * Remove the specified resource from storage.
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($agent_id)
    {
        $agent = Agent ::findOrFail($agent_id);
        $agent->delete();
        return redirect('/agent/login')->with('success', 'Agent Information Deleted');
    }
}

resources/views/agent/index.blade.php
@extends('layouts.adminmain')

@section('content')

    <style type="text/css">
        .zoomin img {
            height: 200px;
            width: 200px;
            -webkit-transition: all 2s ease;
            -moz-transition: all 2s ease;
            -ms-transition: all 2s ease;
            transition: all 2s ease;
        }
        .zoomin img:hover {
            width:310px;
            height:310px;
        }
    </style>
    <div class="container">
        <div class="col-xl-20 col-lg-18 col-md-22 col-sm-19 col-19">
            <div class="card-header1">
                <div class="row justify-content-center">
                    <div class="card-body">
                        <div class="col-md">
                            <B><BR> <CENTER> <h3> Welcome Back {{Auth::guard('agent')->user()->agent_name}}<hr>
{{--                                                Homestay Management System </h3></CENTER></B><hr><br>--}}
                                                    <CENTER> <h3> Unit To Be Added</h3></CENTER>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
            <div class="container-fluid dashboard-content">
            <!-- ============================================================== -->
            <!-- pageheader -->
            <!-- ============================================================== -->
                    <div class="row">
                        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-15 col-15">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="text-muted">Upcoming Unit</h5><hr>
                                    <div class="metric-value d-inline-block">
                                        <h1 class="mb-3">English Unit</h1>

                                        <a href="{{route('homestay.create')}}">
                                        <<img src="usertemp/img/homestay/signage/index 1.jpg" align="center" width="400">
                                        </a>
                                    </div>
                                    <hr>
                                    <div class=" float-bottom text-success font-weight-bold">
                                        <span><i class="fa fa-fw fa-arrow text-success"></i></span><span>Single Storey Unit with: </span><br>
                                    </div>

                                    <div class=" float-bottom  font-weight-regular">
                                        <span><i class="fa fa-fw fa-arrow text-danger"></i></span><span>* 3 Bedroom</span>
                                    </div>
                                    <div class=" float-bottom  font-weight-regular">
                                        <span><i class="fa fa-fw fa-arrow text-danger"></i></span><span>* 3 Bathroom</span>
                                    </div>
                                    <div class=" float-bottom  font-weight-regular">
                                        <span><i class="fa fa-fw fa-arrow text-danger"></i></span><span>* Membership</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-9 col-md-9 col-sm-15 col-15">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="text-muted">Upcoming Unit</h5><hr>
                                    <div class="metric-value d-inline-block">
                                        <h1 class="mb-3">Semi-Detachê</h1>

                                        <a href="{{route('homestay.create')}}">
                                            <img src="usertemp/img/homestay/signage/index 2.jpg" align="center" width="410">
                                        </a>                                        </div>
                                    <hr>

                                    <div class=" float-bottom text-success font-weight-bold">
                                        <span><i class="fa fa-fw fa-arrow text-success"></i></span><span>2 Storey Unit with: </span><br>
                                    </div>

                                        <div class=" float-bottom  font-weight-regular">
                                            <span><i class="fa fa-fw fa-arrow text-danger"></i></span><span>* 4 Bedroom</span>
                                        </div>
                                        <div class=" float-bottom  font-weight-regular">
                                            <span><i class="fa fa-fw fa-arrow text-danger"></i></span><span>* 3 Bathroom</span>
                                        </div>
                                        <div class=" float-bottom  font-weight-regular">
                                            <span><i class="fa fa-fw fa-arrow text-danger"></i></span><span>* Membership</span>
                                        </div>
                                </div>
                        </div>
                    </div>
                     <br>

                    <center>
                    <div class="col-xl-20 col-lg-18 col-md-22 col-sm-19 col-19">
                        <div class="card">
                            <h2 class="card-header1" >Recent Booking</h2><br>
                            <div class="card-body p-1">
                                <div class="table table-striped table-bordered first">
                                    <table class="table">
                                        <thead class="bg-light">
                                        <tr class="border-0">
                                            <th>Booking ID</th>
                                            <th>Homestay Photos</th>
                                            <th>Guest Name</th>
                                            <th>Guest Phone Number</th>
                                            <th>House Name</th>
                                            <th>House Type</th>
                                            <th>Number Of Room</th>
{{--                                            <th>House Phone Number</th>--}}
                                            <th>Check In Date</th>
                                            <th>Check Out Date</th>
{{--                                            <th>Booking Status</th>--}}
{{--                                            <th>Booking Rate (RM)</th>--}}
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        @foreach($booking as $bookings)
                                            <tr>
                                                <td>{{$bookings->booking_id}}</td>
                                                <td><img src="{{ URL::to('/') }}/images/{{ $bookings->homestay->image }}" class="img-thumbnail" width="200" /></td>
                                                <td><center>{{$bookings->guest->guest_name}}</td>
                                                <td><center>{{$bookings->guest->guest_pnum}}</td>
                                                <td><center>{{$bookings->homestay->house_name}}</td>
                                                <td><center>{{$bookings->homestay->house_type}}</td>
                                                <td><center>{{$bookings->homestay->room_count}}</td>
{{--                                                <td><center>{{$bookings->homestay->house_pnum}}</td>--}}
                                                <td><center>{{$bookings->checkin_date}}</td>
                                                <td><center>{{$bookings->checkout_date}}</td>
{{--                                                <td><center>{{$bookings->booking_status}}</td>--}}
{{--                                                <td><center>{{$bookings->booking_rate}}</td>--}}
                                                <td>
                                                    <a class= "btn btn-rounded btn-primary btn-md" href="{{route('booking.detail', $bookings->booking_id)}}">View </a><br>

                                        @endforeach
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                   </center>
            </div>
    @endsection